# Generated by Django 5.2.9 on 2026-01-04 04:38

import apps.common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_api', '0002_whatsappaccount_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='Si el bot de IA está activo para esta cuenta')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini')], default='gemini', help_text='Proveedor de IA a utilizar', max_length=50)),
                ('api_key', apps.common.fields.EncryptedTextField(help_text='API Key del proveedor (encriptada)')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Prompt del sistema que define el comportamiento del asistente')),
                ('max_history_messages', models.PositiveIntegerField(default=10, help_text='Número máximo de mensajes de historial a enviar al modelo')),
                ('account', models.OneToOneField(help_text='Cuenta de WhatsApp asociada', on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='config_api.whatsappaccount')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
    ]
