# Generated by Django 5.2.9 on 2026-01-03 15:01

import apps.common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre interno de la cuenta', max_length=100)),
                ('phone_number_id', models.CharField(help_text='Phone Number ID de Meta', max_length=50, unique=True)),
                ('business_account_id', models.CharField(help_text='Business Account ID de Meta', max_length=50)),
                ('access_token', apps.common.fields.EncryptedTextField(help_text='Permanent Access Token de Meta (Encriptado)')),
                ('webhook_verify_token', apps.common.fields.EncryptedTextField(help_text='Token para verificar webhooks de Meta (Encriptado)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la plantilla (ej: hello_world)', max_length=255)),
                ('language', models.CharField(help_text='Código de idioma (ej: es, en_US)', max_length=10)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('components', models.JSONField(blank=True, default=dict, help_text='Estructura de la plantilla (header, body, footer, buttons)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='config_api.whatsappaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['name', 'language'],
                'unique_together': {('account', 'name', 'language')},
            },
        ),
    ]
