# Generated by Django 5.2.9 on 2026-01-04 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario de esta cuenta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
