# Generated by Django 5.2.9 on 2026-01-02 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Número de teléfono con código de país (ej: 573001234567)', max_length=20)),
                ('name', models.CharField(blank=True, default='', help_text='Nombre del contacto', max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, help_text='URL de la foto de perfil de WhatsApp', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del contacto')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='config_api.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name', 'phone_number'],
                'indexes': [models.Index(fields=['phone_number'], name='contacts_co_phone_n_6d0af4_idx'), models.Index(fields=['account', 'phone_number'], name='contacts_co_account_1efad4_idx')],
                'unique_together': {('account', 'phone_number')},
            },
        ),
    ]
