# Generated by Django 5.2.9 on 2026-01-03 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_api', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha del último mensaje para ordenar inbox', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='config_api.whatsappaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whatsapp_id', models.CharField(db_index=True, help_text='wamid de WhatsApp (identificador único del mensaje)', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('template', 'Template'), ('interactive', 'Interactive'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts')], default='text', max_length=20)),
                ('body', models.TextField(blank=True, help_text='Contenido del mensaje (para mensajes de texto)', null=True)),
                ('media_url', models.URLField(blank=True, help_text='URL del archivo adjunto', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Payload completo del mensaje de Meta')),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_f07e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_message_at'], name='chat_conver_status_438afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('account', 'contact')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['whatsapp_id'], name='chat_messag_whatsap_c9a633_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
    ]
